# Banco de dados
spring.application.name=helpdesk37bpmm
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Sessão válida por duas horas, mesmo após fechar o navegador.
server.servlet.session.timeout=2h
server.servlet.session.cookie.max-age=2h
