-- Garante que instalações novas recebam o esquema completo pelo Flyway.
-- Em bancos existentes, IF NOT EXISTS preserva as tabelas e os dados atuais.
CREATE TABLE IF NOT EXISTS tb_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posto_graduacao VARCHAR(255) NOT NULL,
    qra VARCHAR(255) NOT NULL,
    re VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    senha_hash VARCHAR(255) NOT NULL,
    troca_senha_obrigatoria BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_tb_usuario_re UNIQUE (re),
    CONSTRAINT uk_tb_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS tb_tecnico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_tb_tecnico_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_tb_tecnico_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE TABLE IF NOT EXISTS tb_chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao BIGINT DEFAULT 0,
    solicitante_id BIGINT NOT NULL,
    aberto_por_id BIGINT,
    tecnico_id BIGINT,
    descricao TEXT NOT NULL,
    categoria VARCHAR(255),
    local_atendimento VARCHAR(255),
    motivo_cancelamento TEXT,
    solucao TEXT,
    prioridade VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    resolvido_por VARCHAR(255),
    data_abertura TIMESTAMP NOT NULL,
    data_ultima_interacao TIMESTAMP,
    data_finalizacao TIMESTAMP,
    CONSTRAINT fk_tb_chamados_solicitante
        FOREIGN KEY (solicitante_id) REFERENCES tb_usuario (id),
    CONSTRAINT fk_tb_chamados_aberto_por
        FOREIGN KEY (aberto_por_id) REFERENCES tb_usuario (id),
    CONSTRAINT fk_tb_chamados_tecnico
        FOREIGN KEY (tecnico_id) REFERENCES tb_tecnico (id)
);

CREATE TABLE IF NOT EXISTS tb_atendimento_mike_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    categoria VARCHAR(255),
    descricao_problema TEXT NOT NULL,
    sugestoes_apresentadas TEXT,
    possui_orientacao_testavel BOOLEAN NOT NULL DEFAULT FALSE,
    resultado VARCHAR(255),
    chamado_gerado_id BIGINT,
    data_inicio TIMESTAMP NOT NULL,
    data_conclusao TIMESTAMP,
    CONSTRAINT uk_tb_atendimento_mike_chamado UNIQUE (chamado_gerado_id),
    CONSTRAINT fk_tb_atendimento_mike_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id),
    CONSTRAINT fk_tb_atendimento_mike_chamado
        FOREIGN KEY (chamado_gerado_id) REFERENCES tb_chamados (id)
);

CREATE TABLE IF NOT EXISTS tb_relato_erro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tipo_erro VARCHAR(255) NOT NULL,
    observacao TEXT,
    data_relato TIMESTAMP NOT NULL,
    CONSTRAINT fk_tb_relato_erro_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id)
);

CREATE INDEX IF NOT EXISTS idx_tb_chamados_solicitante
    ON tb_chamados (solicitante_id);
CREATE INDEX IF NOT EXISTS idx_tb_chamados_aberto_por
    ON tb_chamados (aberto_por_id);
CREATE INDEX IF NOT EXISTS idx_tb_chamados_tecnico
    ON tb_chamados (tecnico_id);
CREATE INDEX IF NOT EXISTS idx_tb_atendimento_mike_usuario
    ON tb_atendimento_mike_ia (usuario_id);
CREATE INDEX IF NOT EXISTS idx_tb_relato_erro_usuario
    ON tb_relato_erro (usuario_id);
